version: '3.4'

services:
  classplanner_app:
    image: classplanner_app:${VERSION}
    container_name: classplanner_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      JDBC_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      JDBC_DATASOURCE_USERNAME: ${POSTGRES_USER}
      JDBC_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
