services:
  install:
    image: maven:3.6.3-openjdk-17
    container_name: maven
    working_dir: /usr/code/app
    command: ['mvn', 'clean', 'install']
    volumes:
      - ${PWD}:/usr/code/app
      - ${HOME}/.m2/:/root/.m2
