-- Creating user table

CREATE SEQUENCE USER_SEQUENCE START 1;
CREATE TABLE _USER (
    ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('USER_SEQUENCE'),
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

-- Create default unauthenticated user
INSERT INTO _USER (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD)
VALUES ('Unauthenticated', 'User', 'test@test.com', 'NONE');
